Correct alias name
zhenggen-xu/sonic-buildimage pull request #58
Opened 2020-03-17 17:16 UTC by vasant17

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2020-03-17 20:25 UTC, samaity requested changes

2020-03-17 20:25 UTC, samaity commented on platform/vs/docker-sonic-vs/platform.json
> +            "alias_at_lanes": "fortyGigE/0,fortyGigE/1,fortyGigE/2,fortyGigE/3",
Kindly update `fortyGigE` to `fortyGigE0` wherever required.

2020-03-17 20:54 UTC, zhenggen-xu commented
Can we include all ever tests were done for the PR?

2020-03-18 00:51 UTC, vasant17 commented on platform/vs/docker-sonic-vs/platform.json
> +            "alias_at_lanes": "fortyGigE/0,fortyGigE/1,fortyGigE/2,fortyGigE/3",
Done. Thanks!

2020-03-22 04:59 UTC, zhenggen-xu approved these changes

2020-03-22 04:59 UTC, merged